version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "tests/**"
      - "app/tests/**"

  - package-ecosystem: "bun"
    directory: "/app"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "tests/**"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
