version: "3.8"

services:
  # Test with pnpm
  e2e-pnpm:
    build:
      context: ..
      dockerfile: e2e/Dockerfile
    container_name: pastoralist-e2e-pnpm
    volumes:
      - ../dist:/app/pastoralist:ro
      - ./results:/app/results
    working_dir: /app
    command: /app/scripts/run-e2e-tests.sh
    environment:
      - NODE_ENV=test
      - IS_DEBUGGING=true
      - PACKAGE_MANAGER=pnpm

  # Interactive shell for manual testing
  e2e-shell:
    build:
      context: ..
      dockerfile: e2e/Dockerfile
    container_name: pastoralist-e2e-shell
    volumes:
      - ../dist:/app/pastoralist:ro
      - ./results:/app/results
    working_dir: /app
    command: /bin/sh
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=test
      - IS_DEBUGGING=true

  # Test with npm
  e2e-npm:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.npm
    container_name: pastoralist-e2e-npm
    volumes:
      - ../dist:/app/pastoralist:ro
      - ./results:/app/results
    working_dir: /app
    command: /app/scripts/run-e2e-tests.sh
    environment:
      - NODE_ENV=test
      - IS_DEBUGGING=true
      - PACKAGE_MANAGER=npm

  # Test with yarn
  e2e-yarn:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.yarn
    container_name: pastoralist-e2e-yarn
    volumes:
      - ../dist:/app/pastoralist:ro
      - ./results:/app/results
    working_dir: /app
    command: /app/scripts/run-e2e-tests.sh
    environment:
      - NODE_ENV=test
      - IS_DEBUGGING=true
      - PACKAGE_MANAGER=yarn
