name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - run: bun install --frozen-lockfile

      - run: bun test tests/unit/
        env:
          CI: true

      - run: bun run build-dist

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
